[tool.poetry]
name = "octopoes"
version = "0.1.0"
description = "KAT's knowledge graph engine"
authors = [""]
license = "EUPL"

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.vulture]
min_confidence = 90

[tool.pylint.format]
max-line-length = "120"

[tool.pylint."MESSAGES CONTROL"]
disable = ["R0914","W1514"] # Ignore too-many-local-variables and unspecified encodings
extension-pkg-whitelist = "pydantic" # Ignore pydantic import checks

[tool.black]
line-length = 120
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
pydantic = "^1.10.2"
fastapi = "^0.85.1"
fastapi-utils = "^0.2.1"
uvicorn = "^0.19.0"
pika = "^1.3.1"
PyYAML = "^6.0"
setuptools = "^65.5.0"
dnspython = "^2.2.1"
kombu = "^5.2.4"
celery = "^5.2.7"
pyparsing = "^3.0.9"
packaging = "^21.3"
tldextract = "^3.4.0"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.10.0"
vulture = "^2.6"
mypy = "^0.982"
pylint = "^2.15.4"
black = "^22.10.0"
flake8 = "^5.0.4"
robotframework = "^6.0"
robotframework-requests = "^0.9.3"
robotframework-tidy = "^3.3.1"
robotframework-httplibrary = "^0.4.2"
