name: Run the test suite


on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  Tests:

    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - uses: actions/checkout@v1

      - name: Build the images
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f base.yml -f .ci/docker-compose.yml build

      - name: Run octopoes unit tests
        run: docker-compose -f base.yml -f .ci/docker-compose.yml run --rm octopoes_unit
